[package]
name = "matrix-canonical-json"
version = "0.1.0"
authors = ["Devin Ragotzy <devin.ragotzy@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.57"
serde = "1.0.114"
itoa = "0.4.6"
ryu = "1.0.5"

[dev-dependencies]
serde_derive = "1.0.114"